apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: badra-info-tls
spec:
  secretName: badra-info
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: badra.info
  dnsNames:
    - badra.info
    - www.badra.info
